package cli

import (
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

func newInitCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "init [dir]",
		Short: "Detect the project and write chmura.yaml",
		Args:  usageArgs(cobra.MaximumNArgs(1)),
		RunE: func(cmd *cobra.Command, args []string) error {
			dir := "."
			if len(args) == 1 {
				dir = args[0]
			}
			return runInit(cmd.OutOrStdout(), dir)
		},
	}
}

// runInit inspects dir and writes dir/chmura.yaml. It never overwrites an
// existing manifest, and refuses when no application source is found.
func runInit(out io.Writer, dir string) error {
	manifest := filepath.Join(dir, "chmura.yaml")
	if _, err := os.Stat(manifest); err == nil {
		return &usageError{fmt.Errorf("chmura.yaml already exists in %s", dir)}
	}
	// Detection reads only declarative sources; for now that is a Dockerfile.
	if _, err := os.Stat(filepath.Join(dir, "Dockerfile")); err != nil {
		return &usageError{fmt.Errorf("no application source found in %s: expected a Dockerfile", dir)}
	}

	name, err := projectName(dir)
	if err != nil {
		return err
	}
	if err := os.WriteFile(manifest, []byte(generateManifest(name)), 0o644); err != nil {
		return err
	}
	fmt.Fprintf(out, "Wrote %s\n", manifest)
	return nil
}

func projectName(dir string) (string, error) {
	abs, err := filepath.Abs(dir)
	if err != nil {
		return "", err
	}
	return filepath.Base(abs), nil
}

// generateManifest returns a minimal, valid chmura.yaml. What cannot be derived
// from a Dockerfile is written as commented scaffolding, never guessed.
func generateManifest(name string) string {
	return fmt.Sprintf(`# Generated by chmura init. Fill in the commented scaffolding below —
# Chmura does not guess ports, health checks, endpoints, or values.
version: 1
name: %s

applications:
  %s:
    source:
      context: .
      dockerfile: Dockerfile

    # ports:
    #   http: { number: 8080, protocol: http, visibility: project }

    # env:
    #   LOG_LEVEL: info

    # health:
    #   check: { http: { path: /healthz, port: http } }
    #   startup-timeout: 2m

# volumes: {}
# endpoints: {}
`, name, name)
}

// usageArgs wraps a positional-args validator so a violation maps to a usage
// error (exit 2) rather than an execution error.
func usageArgs(inner cobra.PositionalArgs) cobra.PositionalArgs {
	return func(cmd *cobra.Command, args []string) error {
		if err := inner(cmd, args); err != nil {
			return &usageError{err}
		}
		return nil
	}
}
